import type { Incident, Service } from './types'

export const incidents: Incident[] = [
  {
    id: '1',
    title: 'Payment API latency',
    service: 'payments-api',
    severity: 'P1',
    status: 'open',
    summary: 'P95 latency crossed 2s for card authorizations.',
    createdAt: '2026-09-18T17:30:00Z',
    updatedAt: '2026-09-18T17:42:00Z',
  },
  {
    id: '2',
    title: 'Checkout errors',
    service: 'checkout-web',
    severity: 'P2',
    status: 'acknowledged',
    summary: 'Intermittent 502s on the checkout confirmation step.',
    createdAt: '2026-09-18T16:49:00Z',
    updatedAt: '2026-09-18T17:11:00Z',
  },
  {
    id: '3',
    title: 'Search degraded',
    service: 'search-service',
    severity: 'P3',
    status: 'open',
    summary: 'Search indexing fell behind after a batch import.',
    createdAt: '2026-09-18T15:10:00Z',
    updatedAt: '2026-09-18T16:02:00Z',
  },
  {
    id: '4',
    title: 'Payment webhook retries',
    service: 'payments-api',
    severity: 'P2',
    status: 'open',
    summary: 'Webhook delivery is retrying above the normal threshold.',
    createdAt: '2026-09-18T14:25:00Z',
    updatedAt: '2026-09-18T14:40:00Z',
  },
  {
    id: '5',
    title: 'Mobile login timeout',
    service: 'identity',
    severity: 'P2',
    status: 'closed',
    summary: 'A regional identity provider timeout has recovered.',
    createdAt: '2026-09-17T20:15:00Z',
    updatedAt: '2026-09-17T20:45:00Z',
  },
  {
    id: '6',
    title: 'Email delivery delay',
    service: 'notifications',
    severity: 'P3',
    status: 'closed',
    summary: 'Queued transactional email was delayed during provider maintenance.',
    createdAt: '2026-09-17T11:15:00Z',
    updatedAt: '2026-09-17T12:05:00Z',
  },
]
export const services: Service[] = [
  {
    name: 'payments-api',
    owner: 'Commerce Platform',
    health: 'critical',
    uptime: 98.2,
    latency: 1840,
  },
  { name: 'checkout-web', owner: 'Storefront', health: 'degraded', uptime: 99.1, latency: 620 },
  { name: 'search-service', owner: 'Discovery', health: 'healthy', uptime: 99.98, latency: 115 },
  { name: 'identity', owner: 'Core Experience', health: 'healthy', uptime: 99.99, latency: 92 },
]
